stages:
  - build_assets
  - build_site
  - deploy


# Build the css & js using Webpack
webpack:
  image: node:8
  stage: build_assets
  environment:
    name: production
  only:
    - master

  cache:
    key: ${CI_JOB_NAME}
    paths:
    - node_modules/

  script:
  - npm install
  - npm run webpack
  artifacts:
    expire_in: 30 minutes
    paths:
    - dist
    - data


# Build the Hugo site
hugo:
    image: registry.gitlab.com/pages/hugo:latest
    stage: build_site
    environment:
      name: production
    only:
      - master

    variables:
      GIT_STRATEGY: fetch

    script:
    - hugo
    artifacts:
      paths:
      - dist


# cp the Webpack build + static assets (images, etc...) to the s3 bucket
deploy_to_s3:
  image: python:3.6.5
  stage: deploy
  environment:
    name: production
  dependencies:
    - hugo
  only:
    - master

  cache:
    key: ${CI_JOB_NAME}
    paths:
    - .cache/
    - venv/
  variables:
    GIT_STRATEGY: fetch
    PUBLIC_DIR: dist
    S3_BUCKET: www.iceweb.co
    S3_BUCKET_NAKED: iceweb.co
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache

  before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade --requirement requirements.txt
  script:
  # HTML files
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
    --exclude "*" --include "*.html"
    --cache-control="no-cache"
  # CSS, JS files
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
    --exclude "*" --include "*.css" --include "*.js"
    --cache-control="max-age=31536000"
  # static assets like jpg, png, etc...
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
    --exclude "*" --include "*.jpg" --include "*.png" --include "*.svg"
    --include "*.ico" --include "*.svg"
    --cache-control="max-age=604800"
  # everything else
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
  # update website hosting configuration
  - >
    aws s3api put-bucket-website --bucket $S3_BUCKET
    --website-configuration file://config/s3.www.iceweb.co.json
  - >
    aws s3api put-bucket-website --bucket $S3_BUCKET_NAKED
    --website-configuration file://config/s3.iceweb.co.json
  # Update s3 redirect using my python script
  - >
    python scripts/putredir.py --bucket $S3_BUCKET config/_redirects
