stages:
  - build_assets
  - build_site
  - deploy


# Build the css & js using Webpack
webpack:
  image: node:8
  stage: build_assets
  environment:
    name: production
  only:
    - master

  cache:
    key: ${CI_JOB_NAME}
    paths:
    - node_modules/

  before_script:
  - npm install
  script:
  - npm run build
  artifacts:
    expire_in: 60 minutes
    paths:
    - static
    - data/assets


# Build the Hugo site
hugo:
    image: registry.gitlab.com/pages/hugo:latest
    stage: build_site
    environment:
      name: production
    only:
      - master

    script:
    - hugo
    artifacts:
      paths:
      - public


# cp the Webpack build + static assets (images, etc...) to the s3 bucket
deploy_to_s3:
  image: python:latest
  stage: deploy
  environment:
    name: production
  dependencies:
    - hugo
  only:
    - master

  cache:
    key: ${CI_JOB_NAME}
    paths:
    - .cache/
    - venv/
  variables:
    PUBLIC_DIR: public
    S3_BUCKET: www.iceweb.co
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache

  before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade awscli
  script:
  # HTML files
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
    --exclude "*" --include "*.html"
    --cache-control="no-cache"
  # CSS, JS files
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
    --exclude "*" --include "*.css" --include "*.js"
    --cache-control="max-age=31536000"
  # static assets like jpg, png, etc...
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET/gsuite/static --recursive
    --exclude "*"
    --include "*.jpg" --include "*.png" --include "*.svg" --include "*.ico"
    --cache-control="max-age=86400"
  # everything else
  - >
    aws s3 mv $PUBLIC_DIR/ s3://$S3_BUCKET --recursive
  # update website hosting configuration
  - >
    aws s3api put-bucket-website --bucket $S3_BUCKET
    --website-configuration file://website.json
