baseURL: https://www.iceweb.co/
disableKinds: [taxonomy, taxonomyTerm, RSS]
publishDir: dist
resourceDir: cache
imaging:
  resampleFilter: CatmullRom

disableLanguages: []
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  ar:
    languageName: "العربية"
    title: "ICEWEB"
    params:
      languageDirection: "rtl"
      description: >
        We are a G Suite partner based in Riyadh, Saudi Arabia.
        We do data migration, on-site user & admin traning
  en:
    languageName: "English"
    title: "ICEWEB"
    params:
      languageDirection: "ltr"
